### PR TITLE
Fix for #47 Don't try to `%s` format in error text because it can cause `ValueError`

### PR DESCRIPTION
**Pull request by sheagcraig**
Also, this reports the returncode of failed scripts, then logs the
stderr output.

### CODE REVIEW

**Comment by erikng** [comment]
Can you show me an example log with the error?

**Comment by sheagcraig** [comment]
```
2020-03-17 20:19:25.948 Python[977:8489] [InstallApplications] Starting root script: /Library/installapplications/munki_dep.py
2020-03-17 20:19:25.951 Python[977:8489] [InstallApplications] Running Script: /Library/installapplications/munki_dep.py 
Traceback (most recent call last):
  File "/Library/installapplications/installapplications.py", line 733, in <module>
    main()
  File "/Library/installapplications/installapplications.py", line 697, in main
    runrootscript(path, donotwait)
  File "/Library/installapplications/installapplications.py", line 226, in runrootscript
    iaslog('Output from %s on stderr but ran successfully: %s' %
  File "/Library/installapplications/installapplications.py", line 57, in iaslog
    NSLog('[InstallApplications] ' + text)
ValueError: Too few arguments for format string [cur:1/len:1]
```

There's the relevant part.

As I mentioned in chat the other day, I can't actually replicate this in the interpreter, but yet I'm still seeing it occasionally. The `munki_dep.py` script it's trying to run still ran it's managedsoftwareupdate run, as I can see in the Munki logs, the timestamps for the run start after IA has `ValueError`'d out.

**Comment by sheagcraig** [comment]
How's this looking? I can resubmit if needed!

**Comment by erikng** [comment]
Would .format be more appropriate? My style and the PR are more python 2-style

**Comment by sheagcraig** [comment]
Yeah, I just matched it to what was already there. I'm done with straight up fstrings if that's fine with you.

**Comment by sheagcraig** [comment]
If you're itching for it, I can do a PR to convert all of the `%s` formatting to f-strings, but it probably doesn't make sense to do that as part of this PR.

**Comment by sheagcraig** [comment]
This is still failing on new deployments for us. How are we looking?

**Comment by erikng** [comment]
Have you tested latest master branch? I think I accidentally fixed this in another diff a few weeks ago.

**Comment by sheagcraig** [comment]
https://github.com/macadmins/installapplications/commit/dffbe0a83854bb0df2ae5e6bf55a63034eaa732a
That ought to do it too. Cool cool! Thanks man!

**Pull request closed without merging**
