### PR TITLE
Add file extension

### PR DESCRIPTION
**Pull request by flammable**
Add .sh extension to match documentation

### CODE REVIEW

**Comment by erikng** [comment]
Actually let's keep the extension off so later we can move to zsh.

**Comment by flammable** [comment]
It looks like the shebang is already `#!/bin/zsh`. Should I change the extension to .zsh, our just update README.md to remove the extension? Either way, I guess README.md would need to be updated.

**Comment by erikng** [comment]
That's actually why the extension was removed lol. Just remembered. Yeah just change the readme instead.

**Comment by flammable** [comment]
Okay, I think I did that correctly!

**Comment by erikng** [comment]
Yep looks good. Squashing it down to a single commit since there was multiple things commits. Thanks again.

**Pull request merged**
